### ISSUE TITLE
EPIC: As a new user, I can enter my name, email address and password in order to create an account so that I can use the application

### ISSUE THREAD

**Issue by AndyD20** [ansuj9123/wm4-quiz-app#5]
This epic will cover the initial set-up of the application, including the infrastructure set-up of deploying the boilerplate app to a hosting service, and setting up an SQL server to store user information in. It should also include the basic user registration page so that a user can submit their details, which will later allow them to log into the system.

Linked Tasks:

- [ ] https://github.com/ansuj9123/wm4-quiz-app/issues/3
- [ ] https://github.com/ansuj9123/wm4-quiz-app/issues/8
- [ ] https://github.com/ansuj9123/wm4-quiz-app/issues/13
- [ ] https://github.com/ansuj9123/wm4-quiz-app/issues/11
- [ ] https://github.com/ansuj9123/wm4-quiz-app/issues/9
